version: 2.4.4
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies --max-workers=2 --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: traceroute google.com
  moduleStatisticsReport:
    environment:
      JVM_OPTS: -Xmx4096m
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Execute Data Processing
          command: ./gradlew reportModuleStatistics --max-workers=2 --stacktrace --no-configure-on-demand
  lint:
    environment:
      JVM_OPTS: -Xmx4096m
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint
          command: traceroute google.com
  lintReport:
    environment:
      JVM_OPTS: -Xmx4096m
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint Report
          command: ./gradlew lintStatisticsReport --max-workers=2 --stacktrace

workflows:
  version: 2
  check:
    jobs:
      - build
      - lint
  statisticsReport:
    triggers:
      - schedule:
          cron: "0 8 * * *" # Every Day at 8:00 UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - moduleStatisticsReport
      - lintReport

